SQLMAP_API_OPTIONS = {
    "crawlDepth", "osShell", "getUsers", "getPasswordHashes", "excludeSysDbs", "ignoreTimeouts",
    "regData", "prefix", "code", "googlePage", "skip", "query", "randomAgent", "osPwn", "authType",
    "safeUrl", "requestFile", "predictOutput", "wizard", "stopFail", "forms",
    "uChar", "pivotColumn", "dropSetCookie", "smart", "paramExclude", "risk",
    "sqlFile", "rParam", "getCurrentUser", "notString", "getRoles", "getPrivileges",
    "testParameter", "tbl", "charset", "trafficFile", "osSmb", "level",
    "dnsDomain", "skipStatic", "secondOrder", "outputDir", "skipWaf", "timeout",
    "firstChar", "torPort", "getComments", "binaryFields", "checkTor", "commonTables",
    "direct", "tmpPath", "titles", "getSchema", "identifyWaf", "paramDel",
    "safeReqFile", "regKey", "murphyRate", "limitStart", "crawlExclude", "flushSession",
    "loadCookies", "csvDel" ",", "offline", "method", "tmpDir", "disablePrecon",
    "osBof", "testSkip", "invalidLogical", "getCurrentDb", "hexConvert", "proxyFile",
    "answers", "host", "dependencies", "cookie", "proxy", "regType",
    "optimize", "limitStop", "search", "uFrom", "noCast", "testFilter",
    "ignoreCode", "eta", "csrfToken", "threads", "logFile", "os",
    "col", "rFile", "proxyCred", "verbose", "isDba", "updateAll",
    "privEsc", "forceDns", "getAll", "invalidBignum", "regexp", "getDbs",
    "freshQueries", "uCols", "smokeTest", "wFile", "udfInject", "invalidString",
    "tor", "forceSSL", "beep", "noEscape", "configFile", "scope",
    "authFile", "torType" "SOCKS5", "regVal", "dummy", "checkInternet", "safePost",
    "skipUrlEncode", "referer", "liveTest", "purgeOutput", "retries", "extensiveFp",
    "dumpTable", "getColumns", "batch", "headers", "authCred", "osCmd",
    "suffix", "dbmsCred", "regDel", "shLib", "sitemapUrl", "timeSec",
    "msfPath", "dumpAll", "getHostname", "sessionFile", "disableColoring", "getTables",
    "safeFreq", "agent", "webRoot", "lastChar", "string", "dbms",
    "dumpWhere", "tamper", "ignoreRedirects" "hpp", "runCase", "delay",
    "evalCode", "cleanup", "csrfUrl", "getBanner", "profile", "regRead",
    "bulkFile", "db", "excludeCol", "dumpFormat", "alert", "harFile",
    "Connection", "user", "parseErrors", "getCount", "dFile", "data",
    "regAdd", "ignoreProxy", "mobile", "googleDork", "saveConfig", "sqlShell",
    "tech", "textOnly", "cookieDel", "commonColumns", "keepAlive"
}
